#!/bin/sh

sudo apt-get install build-essential
sudo apt-get install ruby ri rdoc ruby1.8-dev irb1.8 
wget http://rubyforge.org/frs/download.php/70696/rubygems-1.3.7.tgz
tar xvzf rubygems-1.3.7.tgz
cd rubygems-1.3.7
sudo ruby setup.rb
cd ..
rm rubygems-1.3.7.tgz
rm -r rubygems-1.3.7
sudo ln -s /usr/bin/gem1.8 /usr/local/bin/gem
sudo ln -s /usr/bin/ruby1.8 /usr/local/bin/ruby
sudo ln -s /usr/bin/rdoc1.8 /usr/local/bin/rdoc
sudo ln -s /usr/bin/ri1.8 /usr/local/bin/ri
sudo ln -s /usr/bin/irb1.8 /usr/local/bin/irb
sudo gem install sinatra --no-rdoc --no-ri
sudo gem install haml --no-rdoc --no-ri
sudo gem install configatron --no-rdoc --no-ri


